from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.honeypotindex, name='honeypot'),
    url(r'^json/(?:(?P<honeypot_id>[0-9]+)/)?$', views.honeypotjson, name='honeypotjson'),
    url(r'^table/$', views.honeypot_table, name='honeypot_table'),
    url(r'^add/$', views.addhoneypot, name='addhoneypot'),
    url(r'^delete/(?P<honeypot_id>[0-9]+)/$', views.deletehoneypot, name='deletehoneypot'),
    url(r'^edit/$', views.edithoneypot, name='edithoneypot'),
    url(r'^deploy/$', views.deployhoneypot, name='deployhoneypot'),
    url(r'^deploy/json/(?:(?P<deployment_id>[0-9]+)/)?$', views.deploymentjson, name='deploymentjson'),
    url(r'^deploy/table/$', views.deployment_table, name='deployment_table'),
    url(r'^deploy/add/$', views.deploymentadd, name='deploymentadd'),
    url(r'^deploy/add/json/$', views.deploymentaddjson, name='deploymentaddjson'),
    url(r'^deploy/build/(?:(?P<deployment_id>[0-9]+)/)?$', views.deploymentbuild, name='deploymentbuild'),
    url(r'^deploy/build/(?P<deployment_id>[0-9]+)/progress/$', views.deploymentbuildprogress, name='deploymentbuildprogress'),
    url(r'^deploy/build/(?P<deployment_id>[0-9]+)/progress/delete/$', views.deploymentbuildprogressdelete, name='deploymentbuildprogressdelete'),
    url(r'^deploy/delete/(?P<deployment_id>[0-9]+)/$', views.deploymentdelete, name='deploymentdelete'),
    url(r'^deploy/start/(?:(?P<deployment_id>[0-9]+)/)?$', views.deploymentstart, name='deploymentstart'),
    url(r'^deploy/stop/(?:(?P<deployment_id>[0-9]+)/)?$', views.deploymentstop, name='deploymentstop'),
    url(r'^deploy/status/(?:(?P<deployment_id>[0-9]+)/)?$', views.deploymentstatus, name='deploymentstatus'),
    url(r'^deploy/ports/(?P<deployment_id>[0-9]+)/$', views.deploymentports, name='deploymentports'),
    url(r'^deploy/binaries/(?:(?P<deployment_id>[0-9]+)/)?$', views.deploymentbinaries, name='deploymentbinaries'),
    url(r'^deploy/binaries/(?P<deployment_id>[0-9]+)/table/$', views.deploymentbinaries_table, name='deploymentbinaries_table'),
    url(r'^deploy/binaries/download/(?P<deployment_id>[0-9]+)/(?P<filename>.*)/$', views.deploymentbinariesdownload, name='deploymentbinariesdownload'),
    url(r'^deploy/binaries/upload/(?P<deployment_id>[0-9]+)/(?P<filename>.*)/$', views.deploymentbinariesvt, name='deploymentbinariesvt'),
    url(r'^deploy/logs/(?:(?P<deployment_id>[0-9]+)/)?$', views.deploymentlogs, name='deploymentlogs'),
    url(r'^deploy/logs/(?P<deployment_id>[0-9]+)/table/$', views.deploymentlogs_table, name='deploymentlogs_table'),
    url(r'^deploy/logs/(?P<deployment_id>[0-9]+)/(?P<filename>.*)/$', views.deploymentlogview, name='deploymentlogview'),
    url(r'^deploy/logs/addmonitor/(?P<deployment_id>[0-9]+)/(?P<filename>.*)/$', views.deploymentlogaddmonitor, name='deploymentlogaddmonitor'),
    url(r'^deploy/logs/removemonitor/(?P<deployment_id>[0-9]+)/(?P<filename>.*)/$', views.deploymentlogremovemonitor, name='deploymentlogremovemonitor'),
    url(r'^deploy/logs/download/(?P<deployment_id>[0-9]+)/(?P<filename>.*)/$', views.deploymentlogdownload, name='deploymentlogdownload'),
]